VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box     = "drupaltraining" 
  config.vm.box_url = "drupaltraining.box"
  config.vm.hostname = "drupaltraining"
  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.synced_folder "www/", "/var/www", owner: "apache", group: "apache"

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--ioapic", "on"]
    v.memory = 1024
    v.cpus = 2
  end

end
